# Generated by Django 2.0 on 2018-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('car_password', models.CharField(max_length=150)),
                ('car_type', models.CharField(default='normal', max_length=20)),
            ],
        ),
    ]
