# Generated by Django 2.0 on 2018-01-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('venue', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reg_start_date', models.DateField()),
                ('reg_end_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reg_status', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('team_limit', models.IntegerField(default=1)),
                ('status', models.CharField(default='Comming Soon..', max_length=60)),
            ],
        ),
    ]
