# Generated by Django 2.0 on 2018-01-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180105_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='logo_url',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='reg_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='reg_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='reg_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
