# Generated by Django 2.0 on 2018-01-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(default='Comming Soon..', max_length=60)),
                ('img', models.CharField(default='https://', max_length=200)),
                ('logo', models.CharField(default='https://', max_length=200)),
                ('offical_link', models.CharField(default='https://', max_length=200)),
            ],
        ),
    ]
