# Generated by Django 2.0 on 2018-01-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
