# Generated by Django 2.0 on 2018-01-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180105_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_no', models.IntegerField(unique=True)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=30)),
                ('img', models.CharField(default='https://', max_length=200)),
                ('category', models.CharField(choices=[('In', 'Innovation'), ('Me', 'Mechanical')], default='Me', max_length=2)),
                ('department', models.CharField(max_length=20)),
                ('fb_id', models.CharField(default='https://', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('achievement', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
            ],
        ),
    ]
