# Generated by Django 2.0 on 2018-01-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_member_organiser_timeline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
