# Generated by Django 2.0.1 on 2018-01-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180107_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_limit', models.IntegerField(default=1)),
                ('details', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='short_description',
            field=models.CharField(max_length=400),
        ),
        migrations.AddField(
            model_name='workshopplan',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop'),
        ),
    ]
