# Generated by Django 2.0.1 on 2018-01-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180107_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='team_limit',
        ),
    ]
