# Generated by Django 2.0.1 on 2018-01-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_workshop_team_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopFaqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop')),
            ],
        ),
    ]
