# Generated by Django 2.0.1 on 2018-01-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_workshopfaqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='background_url',
            field=models.CharField(default='https://', max_length=200),
        ),
    ]
