# Generated by Django 2.0 on 2018-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_workshop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.IntegerField(default=9560779366),
        ),
    ]
