# Generated by Django 2.0 on 2018-01-09 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_userprofile_user_local'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workshopenrollment',
            unique_together={('user_id', 'workshop_id')},
        ),
    ]
