# Generated by Django 2.0 on 2018-01-09 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_auto_20180109_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopenrollment',
            name='enroll_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workshopenrollment',
            name='payment_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='workshopenrollment',
            unique_together={('user_id', 'workshop_id', 'enroll_status')},
        ),
    ]
