# Generated by Django 2.0 on 2018-01-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180109_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmaterial',
            name='workshop',
        ),
    ]
