# Generated by Django 2.0 on 2018-01-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_projectmaterial_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('Innovation', 'Innovation'), ('Mechanical', 'Mechanical')], default='Mechanical', max_length=20),
        ),
    ]
