# Generated by Django 2.0.1 on 2018-01-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180113_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='user_college',
            field=models.CharField(default='Ajay Kumar Garg College Ghaziabad', max_length=100),
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='user_contact',
            field=models.IntegerField(default='9560779366'),
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='user_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workshopenrollment',
            name='enroll_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workshopenrollment',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
