# Generated by Django 2.0.1 on 2018-01-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180114_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopenrollment',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkshopPlan'),
        ),
    ]
