# Generated by Django 2.0.1 on 2018-01-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_workshopenrollment_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopenrollment',
            name='user_branch',
            field=models.CharField(default='Need to be given', max_length=50),
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='user_year',
            field=models.IntegerField(default=2),
        ),
    ]
